### ISSUE TITLE
improved performance and native compilation by use of GraalVM

### ISSUE THREAD

**Issue by EvenSol** [equinor/neqsim#149]
Can improved performance be obtained by using the GaalVM and possibly compile to native libraries? https://www.graalvm.org/

See how to do it using maven:

https://www.graalvm.org/reference-manual/native-image/

**Comment by EvenSol** [comment]
Try to generate exe file in windows:

Generated manifest with main class 

c:\temp\nativecompiler>native-image -jar neqsim-2.2.3.jar
[neqsim-2.2.3:18776]    classlist:   8,910.64 ms,  0.94 GB
[neqsim-2.2.3:18776]        (cap):  13,788.65 ms,  0.94 GB
[neqsim-2.2.3:18776]        setup:  17,599.23 ms,  0.94 GB
[neqsim-2.2.3:18776]     (clinit):     739.85 ms,  4.34 GB
[neqsim-2.2.3:18776]     analysis:  35,458.99 ms,  4.34 GB
Warning: Aborting stand-alone image build due to unsupported features
Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[neqsim-2.2.3:18776]      [total]:  62,282.92 ms,  4.34 GB
# Printing build artifacts to: c:\temp\nativecompiler\neqsim-2.2.3.build_artifacts.txt
[neqsim-2.2.3:11664]    classlist:   2,028.63 ms,  0.96 GB
[neqsim-2.2.3:11664]        (cap):  11,598.94 ms,  0.96 GB
[neqsim-2.2.3:11664]        setup:  14,919.58 ms,  0.96 GB
[neqsim-2.2.3:11664]     (clinit):     179.08 ms,  1.72 GB
[neqsim-2.2.3:11664]   (typeflow):   3,366.66 ms,  1.72 GB
[neqsim-2.2.3:11664]    (objects):   3,063.33 ms,  1.72 GB
[neqsim-2.2.3:11664]   (features):   1,015.30 ms,  1.72 GB
[neqsim-2.2.3:11664]     analysis:   7,995.59 ms,  1.72 GB
[neqsim-2.2.3:11664]     universe:     642.63 ms,  1.72 GB
[neqsim-2.2.3:11664]      (parse):     674.50 ms,  1.76 GB
[neqsim-2.2.3:11664]     (inline):     981.16 ms,  2.30 GB
[neqsim-2.2.3:11664]    (compile):   8,144.69 ms,  2.97 GB
[neqsim-2.2.3:11664]      compile:  10,483.44 ms,  2.97 GB
[neqsim-2.2.3:11664]        image:   1,303.01 ms,  2.97 GB
[neqsim-2.2.3:11664]        write:     788.84 ms,  2.97 GB
[neqsim-2.2.3:11664]      [total]:  38,403.17 ms,  2.97 GB
# Printing build artifacts to: C:\temp\nativecompiler\neqsim-2.2.3.build_artifacts.txt
Warning: Image 'neqsim-2.2.3' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).

c:\temp\nativecompiler>dir
 Volume in drive C is Windows
 Volume Serial Number is 8A82-E07F

 Directory of c:\temp\nativecompiler

06/01/2022  23:32    <DIR>          .
06/01/2022  23:32    <DIR>          ..
06/01/2022  23:32                34 neqsim-2.2.3.build_artifacts.txt
06/01/2022  23:32        11,430,912 neqsim-2.2.3.exe
06/01/2022  23:28        73,997,557 neqsim-2.2.3.jar
               3 File(s)     85,428,503 bytes
               2 Dir(s)  89,217,228,800 bytes free

c:\temp\nativecompiler>neqsim-2.2.3.exe
Time taken for benchmark flash = 2642

**Comment by EvenSol** [comment]
Did not successfully create a windows dll. Any idea what is the problem?

c:\temp\nativecompiler>native-image -jar neqsim-2.2.3.jar --shared
[neqsim-2.2.3:16284]    classlist:   8,011.52 ms,  0.94 GB
[neqsim-2.2.3:16284]        (cap):  12,052.28 ms,  0.94 GB
[neqsim-2.2.3:16284]        setup:  15,680.91 ms,  0.94 GB
[neqsim-2.2.3:16284]     (clinit):     854.99 ms,  4.99 GB
[neqsim-2.2.3:16284]   (typeflow):   9,465.32 ms,  4.99 GB
[neqsim-2.2.3:16284]    (objects):  20,005.74 ms,  4.99 GB
[neqsim-2.2.3:16284]   (features):   6,488.23 ms,  4.99 GB
[neqsim-2.2.3:16284]     analysis:  38,796.59 ms,  4.99 GB
Warning: Aborting stand-alone image build. Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: com.oracle.bmc.ConfigFileReader. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace:
        at parsing com.mysql.cj.protocol.a.authentication.AuthenticationOciClient.initializePrivateKey(AuthenticationOciClient.java:146)
Call path from entry point to com.mysql.cj.protocol.a.authentication.AuthenticationOciClient.nextAuthenticationStep(NativePacketPayload, List):
        at com.mysql.cj.protocol.a.authentication.AuthenticationOciClient.nextAuthenticationStep(AuthenticationOciClient.java:115)
        at com.mysql.cj.protocol.a.authentication.AuthenticationOciClient.nextAuthenticationStep(AuthenticationOciClient.java:58)
        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:440)
        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210)
        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1369)
        at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
        at com.mysql.cj.CancelQueryTaskImpl$1.run(CancelQueryTaskImpl.java:95)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
        at com.oracle.svm.core.code.IsolateEnterStub.WindowsJavaThreads_osThreadStartRoutine_4bc03aa26f8cdfc97ebd54050e8ae4bce1023851(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.apache.poi.poifs.filesystem.POIFSFileSystem. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace:
        at parsing com.healthmarketscience.jackcess.impl.CompoundOleUtil.<clinit>(CompoundOleUtil.java:60)
Call path from entry point to com.healthmarketscience.jackcess.impl.CompoundOleUtil.<clinit>():
        no path found from entry point to target method


Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[neqsim-2.2.3:16284]      [total]:  62,766.43 ms,  4.99 GB
# Printing build artifacts to: c:\temp\nativecompiler\neqsim-2.2.3.build_artifacts.txt
[neqsim-2.2.3:26184]    classlist:   1,948.35 ms,  0.96 GB
[neqsim-2.2.3:26184]        (cap):  11,851.26 ms,  0.96 GB
[neqsim-2.2.3:26184]        setup:  15,385.56 ms,  0.96 GB
[neqsim-2.2.3:26184]     (clinit):     191.38 ms,  1.72 GB
[neqsim-2.2.3:26184]   (typeflow):   3,851.04 ms,  1.72 GB
[neqsim-2.2.3:26184]    (objects):   3,090.05 ms,  1.72 GB
[neqsim-2.2.3:26184]   (features):   1,478.29 ms,  1.72 GB
[neqsim-2.2.3:26184]     analysis:   9,013.65 ms,  1.72 GB
[neqsim-2.2.3:26184]     universe:     939.79 ms,  1.72 GB
[neqsim-2.2.3:26184]      (parse):     838.20 ms,  1.76 GB
[neqsim-2.2.3:26184]     (inline):     911.37 ms,  2.31 GB
[neqsim-2.2.3:26184]    (compile):   8,349.43 ms,  3.19 GB
[neqsim-2.2.3:26184]      compile:  11,306.89 ms,  3.00 GB
[neqsim-2.2.3:26184]        image:   1,327.67 ms,  3.00 GB
[neqsim-2.2.3:26184]        write:     854.74 ms,  3.00 GB
[neqsim-2.2.3:26184]      [total]:  41,062.11 ms,  3.00 GB
# Printing build artifacts to: C:\temp\nativecompiler\neqsim-2.2.3.build_artifacts.txt
Warning: Image 'neqsim-2.2.3' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).

**Comment by EvenSol** [comment]
successfull when remving mysql and access related libraries from pom:

```
	<!--
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.27</version>
		</dependency>
		-->
		<!-- https://mvnrepository.com/artifact/edu.ucar/netcdf4 -->
		<dependency>
			<groupId>edu.ucar</groupId>
			<artifactId>netcdf4</artifactId>
			<version>4.6.16.1</version>
		</dependency>
		<dependency>
			<groupId>org.ojalgo</groupId>
			<artifactId>ojalgo</artifactId>
			<version>48.4.2</version>
		</dependency>
		<!--
		<dependency>
			<groupId>org.xerial</groupId>
			<artifactId>sqlite-jdbc</artifactId>
			<version>3.34.0</version>
		</dependency>
		<dependency>
			<groupId>net.sf.ucanaccess</groupId>
			<artifactId>ucanaccess</artifactId>
			<version>5.0.1</version>
		</dependency>
		<dependency>
			<groupId>io.airlift</groupId>
			<artifactId>units</artifactId>
			<version>1.6</version>
		</dependency>
		-->
```

c:\temp\nativecompiler>native-image -jar neqsim-2.2.3.jar --shared
[neqsim-2.2.3:17860]    classlist:   7,909.22 ms,  0.94 GB
[neqsim-2.2.3:17860]        (cap):   8,526.19 ms,  0.94 GB
[neqsim-2.2.3:17860]        setup:  12,442.90 ms,  0.94 GB
[neqsim-2.2.3:17860]     (clinit):     424.04 ms,  2.01 GB
[neqsim-2.2.3:17860]   (typeflow):   6,255.46 ms,  2.01 GB
[neqsim-2.2.3:17860]    (objects):   9,322.36 ms,  2.01 GB
[neqsim-2.2.3:17860]   (features):   5,562.42 ms,  2.01 GB
[neqsim-2.2.3:17860]     analysis:  23,265.42 ms,  2.01 GB
[neqsim-2.2.3:17860]     universe:   5,874.28 ms,  3.24 GB
[neqsim-2.2.3:17860]      (parse):   1,320.60 ms,  3.24 GB
[neqsim-2.2.3:17860]     (inline):   1,771.95 ms,  3.51 GB
[neqsim-2.2.3:17860]    (compile):  16,066.05 ms,  3.75 GB
[neqsim-2.2.3:17860]      compile:  21,840.11 ms,  3.75 GB
[neqsim-2.2.3:17860]        image:   3,638.21 ms,  3.75 GB
[neqsim-2.2.3:17860]        write:     819.93 ms,  3.75 GB
[neqsim-2.2.3:17860]      [total]:  77,104.87 ms,  3.75 GB
# Printing build artifacts to: c:\temp\nativecompiler\neqsim-2.2.3.build_artifacts.txt

c:\temp\nativecompiler>dir
 Volume in drive C is Windows
 Volume Serial Number is 8A82-E07F

 Directory of c:\temp\nativecompiler

07/01/2022  00:13    <DIR>          .
07/01/2022  00:13    <DIR>          ..
06/01/2022  23:33               694 derby.log
07/01/2022  00:13             4,895 graal_isolate.h
07/01/2022  00:13             5,007 graal_isolate_dynamic.h
07/01/2022  00:13               190 neqsim-2.2.3.build_artifacts.txt
07/01/2022  00:13        18,650,624 neqsim-2.2.3.dll
07/01/2022  00:06        11,430,912 neqsim-2.2.3.exe
07/01/2022  00:13               277 neqsim-2.2.3.h
07/01/2022  00:11        60,250,590 neqsim-2.2.3.jar
07/01/2022  00:13           186,690 neqsim-2.2.3.lib
07/01/2022  00:13               317 neqsim-2.2.3_dynamic.h
15/12/2021  10:14            43,304 sunmscapi.dll
              11 File(s)     90,573,500 bytes
               2 Dir(s)  88,307,712,000 bytes free

**Comment by EvenSol** [comment]
this seems to work ok to compile executable and linked library on Windows. To be checked on a linux/unix/mac.

**Comment by EvenSol** [comment]
Updated documenttion for how to use paramete rdatabase in MySQL or MS Access. 
https://github.com/equinor/neqsim/wiki/The-NeqSim-parameter-database
