### ISSUE TITLE
GOR fitter for streams with low GOR fails

### ISSUE THREAD

**Issue by EvenSol** [equinor/neqsim#399]
When GOR is low, the GOR fitter sometimes fails:

eg. 

GORfitter gORFItterA6 = new GORfitter("Frig GOR fitter A6", wellStreamFriggOilA6Mixer.getOutStream());
		gORFItterA6.setGOR(1.0);

**Comment by EvenSol** [comment]
![image](https://user-images.githubusercontent.com/41290109/165928919-792aa591-3a99-40d8-beba-fdf06a433a23.png)

**Comment by EvenSol** [comment]
Error when pure gas to Spearator_

12:58:47.813 [Thread-5545] ERROR neqsim.physicalProperties.physicalPropertyMethods.commonPhasePhysicalProperties.conductivity.Conductivity - error        
java.lang.RuntimeException: neqsim.util.exception.IsNaNException: PhaseSrkEos:molarVolume - Variable Molar volume is NaN
        at neqsim.thermo.phase.PhaseEos.init(PhaseEos.java:105) ~[neqsim-2.3.3.jar:?]
        at neqsim.thermo.phase.PhaseSrkEos.init(PhaseSrkEos.java:1) ~[neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemThermo.initAnalytic(SystemThermo.java:1745) ~[neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemSrkEos.initAnalytic(SystemSrkEos.java:1) ~[neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemThermo.init(SystemThermo.java:1684) ~[neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemSrkEos.init(SystemSrkEos.java:1) ~[neqsim-2.3.3.jar:?]
        at neqsim.physicalProperties.physicalPropertyMethods.commonPhasePhysicalProperties.conductivity.PFCTConductivityMethodMod86.calcConductivity(PFCTConductivityMethodMod86.java:115) [neqsim-2.3.3.jar:?]
        at neqsim.physicalProperties.physicalPropertySystem.PhysicalProperties.init(PhysicalProperties.java:251) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.phase.Phase.initPhysicalProperties(Phase.java:439) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.phase.PhaseSrkEos.initPhysicalProperties(PhaseSrkEos.java:1) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.phase.PhaseSrkCPA.initPhysicalProperties(PhaseSrkCPA.java:1) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.phase.PhaseSrkCPAs.initPhysicalProperties(PhaseSrkCPAs.java:1) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemThermo.initPhysicalProperties(SystemThermo.java:2096) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemSrkEos.initPhysicalProperties(SystemSrkEos.java:1) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemSrkCPA.initPhysicalProperties(SystemSrkCPA.java:1) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemSrkCPAs.initPhysicalProperties(SystemSrkCPAs.java:1) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemSrkCPAstatoil.initPhysicalProperties(SystemSrkCPAstatoil.java:1) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemThermo.initProperties(SystemThermo.java:1702) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemSrkEos.initProperties(SystemSrkEos.java:1) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemSrkCPA.initProperties(SystemSrkCPA.java:1) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemSrkCPAs.initProperties(SystemSrkCPAs.java:1) [neqsim-2.3.3.jar:?]
        at neqsim.thermo.system.SystemSrkCPAstatoil.initProperties(SystemSrkCPAstatoil.java:1) [neqsim-2.3.3.jar:?]
        at neqsim.processSimulation.processEquipment.stream.Stream.run(Stream.java:382) [neqsim-2.3.3.jar:?]
        at neqsim.processSimulation.processEquipment.separator.Separator.run(Separator.java:202) [neqsim-2.3.3.jar:?]
        at neqsim.processSimulation.processSystem.ProcessSystem.run(ProcessSystem.java:404) [neqsim-2.3.3.jar:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: neqsim.util.exception.IsNaNException: PhaseSrkEos:molarVolume - Variable Molar volume is NaN
        at neqsim.thermo.phase.PhaseEos.molarVolume(PhaseEos.java:371) ~[neqsim-2.3.3.jar:?]
        at neqsim.thermo.phase.PhaseSrkEos.molarVolume(PhaseSrkEos.java:1) ~[neqsim-2.3.3.jar:?]
        at neqsim.thermo.phase.PhaseEos.init(PhaseEos.java:99) ~[neqsim-2.3.3.jar:?]
        ... 25 more

![image](https://user-images.githubusercontent.com/41290109/165932179-5ba385b3-495a-412d-8506-a9aee24b1fc4.png)
